language: python

python:
  - 3.5

cache: pip

install:
  - pip install -q -r requirements.txt
  - pip install -q flake8

script:
  - flake8 .
  - python3 process.py --video=example.mp4 --output_image=average_frame.jpg --max_frames=5000

notifications:
  email: false

branches:
  only:
    - master
